- src/utils/scope-exit.ts
To support following usage.
```
Promise.using<ScopeExit, void>(new scopeExit().disposer(), async(scopeExit) => {
// do something
return;
});
```
> ScopeExit.disposer returns itself.

- src/islet.ts
The island do not handle rejected promise on initialization process. Node's behavior for unhandled rejected promise is DO NOTHING and Bluebird just shows warnings.
So even if island fails to connect to backend middlewares like redis, currently, island just shows warnings and process stays alive.
We prefer a process termination and restarting automatically rather than staying.
Other islands are restarted in this case. TC finds only common islands work differently and claims to be fixed.
> Exit process if initialization failed

- src/services/amqp-channel-pool-service.ts
- src/services/event-service.ts
- src/services/push-service.ts
- src/services/rpc-service.ts
This pull request contains below various revisions.
- Publish log.eventError when error occured while handling event.
- Set prefetch count for event and rpc consumers
- Bind and unbind exchange immediately when bind fails for preventing auto-delete not triggered.
- Fix AmqpChannelPool to remove timing issues.
> Log event error / Set prefetch count / Trigger auto-delete / Fix AmqpChannelPool

- src/services/push-service.ts
- src/utils/resource-push.ts
Publishing to player exchange frequently causes amqp channel error (404 not found), and it abruptly  closes current channel.
As a workaround, Push-island declares direct exchange 'push.player' and bind it to player exchange using pid as routing-key. We can always publish a message through this permanent exchange without any care.
> Avoiding 404 channel error on pushService.unicast

- src/controllers/endpoint-decorator.ts
- src/spec/schema-decorator.spec.ts
```typescript
@sanitize.query({
'id+maxPlayer': sanitize.ObjectId,
clientid: String,
'offset!': 0,
'limit!': 30
})
```
should be translated like
```typescript
{
id: {
type: '$oid',
__langid: 'id+maxPlayer',
},
clientid: { type: 'string' },
offset: { type: 'number', def: 0, optional: false },
limit: { type: 'number', def: 30, optional: false }
}
```
> Add support to expand langid from property name for @validate @sanitize

- src/services/rpc-service.ts
- src/spec/rpc-spec.ts
Sometimes we got a message like
> [RPC-WARNING] invalid correlationId 450a7641-f692-4057-865f-8d87a6ce253b
or 
> (node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): FatalError: code: ISLAND.FATAL.F0023_RPC_TIMEOUT, msg: RPC(testIng does not return in 60000 ms'
It is followed by 60s timeout for waiting a RPC response. But there is a chance that miss a RPC response despite another island already respond.
> Fix possible missing a RPC response

- package.json
- src/adapters/impl/redis-connection-adapter.ts
Changed from node-redis to redis-bluebird into Redis Connection Adapter
https://github.com/spearhead-ea/island/issues/17
> Refact redis-bluebird instead of node-redis #17

- src/index.ts
- src/services/event-service.ts
- src/utils/error.ts
EventService publishes log.error event when event handlers throw error.
Already it sends 'log.eventError' but that doesn't have enough context so it needs to be revised.
Added AbstractExpectedError class.
This is for the trivial errors which we expect to be occurred in normal scenario and don't need to be logged.
> Change error logging event / Add ExpectedError

- README.md
- src/services/rpc-service.ts
- src/spec/rpc-spec.ts
When the consumer disappears (the queues disappear immediately), all incoming requests timeout occur while the service is restarted.
keeping a constant time queue so that requests are not lost during restart the service
> Merge `Rpc.queue.expire.setting` into `master`

- src/services/rpc-service.ts
- src/spec/rpc-spec.ts
This PR fix below suspicious errors while testing.
```
(node:15798) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): IllegalOperationError: Connection closing
(node:15798) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will termina
it code.
Potentially unhandled rejection [2] Error: Channel ended, no reply will be forthcoming
```
And refactor the `rpc-spec.ts`
> fix(test): UnhandledPromiseRejectionWarning on test

- src/services/rpc-service.ts
- src/spec/rpc-spec.ts
- src/utils/error.ts
fixed the above content
- In the case of an error that has passed through multiple ISLAND, the point of 'occurred error' does not appear correctly.
- the error message is not correct.
fixed wrong error message like 'DUMMY.LOGIC.L0002_WRONG_PARAMETER_SCHEMA' to correctly 'ISLAND.LOGIC.L0002_WRONG_PARAMETER_SCHEMA'
> fix: incorrect delivery of error occuerred on rpc

- src/services/amqp-channel-pool-service.ts
- src/services/event-service.ts
- src/services/rpc-service.ts
It is necessary to set a different prefetch count for each service by weighing throughput and memory requirements obtained by parallelism.
prefetch count can set as env variable, but it can be burden for publishers.
so, make it put default prefetch count in code and override them with environment variables when needed.
> Fix.prefetch.count.modify

- src/controllers/endpoint-decorator.ts
- src/index.ts
- src/spec/endpoint-decorator.spec.ts
>  Current situation in which the admin API can be called through the public gateway is security anxiety. 
> \- tencent
-  We want to call the admin API only through the internal network communication, but it is difficult to apply the separately prepared gateway island depending on whether the admin API is activated or not.
- We thought it preferable to control the admin API calls according to the environment variables in the gateway island.
- So, We have modified the schema on island to develop environment variables that control admin API calls on the gateway island.
- Originally trying to make a decorator for internal checking as `@internal`, but implement it as `@extra`, a generic decorator for use in exceptional situations.
- `@extra({ foo: 'bar' })` decorator is added, which is used …
> feat: add extra decorator 

- .gitignore
- README.md
- package.json
- src/index.ts
- src/islet.ts
- src/services/event-service.ts
- src/services/rpc-service.ts
- src/spec/event-service.spec.ts
- src/spec/rpc.spec.ts
- src/utils/status-exporter.ts
- [island-status-exporter](https://github.com/spearhead-ea/island-status-exporter/pull/1)
- use island-status-exporter module for data collection.
```
{
"cpu": 19.1,
"memory": 51.36,
"measurements": [
{
"type": "rpc",
"tps": 1.33,
"rps": 2.75,
"AvgReceiveMessageTimeByMQ": 135.63,
"AvgExecutionTime": 16.41
}
],
"savedAt": "2017-07-25T05:06:38.688Z",
"instanceId": "localhost"
}
```
RELEASE_CANDIDATE
> feat: island status export file

- src/services/event-service.ts
- src/services/event-subscriber.ts
- src/spec/event-service.spec.ts
- src/spec/push-service.spec.ts
[sphd-issue #412](http://git.sphd.io/support/stt-issues/issues/412)
- If want to change the timestamp, use `DebugEvent`. This should only be used in a development environment.
```
publishEvent(new DebugEvent(new UseEventClass('DebugTimeStamp'), new Date(1004)))
```
- use class and timestamp values ​​as arguments to DebugEvent. `publishedAt` changed to insert timestamp value.
> feat. use 'DebugEvent' to set the timestamp value. RELEASE_CANDIDATE

- src/controllers/endpoint-decorator.ts
- src/spec/schema-decorator.spec.ts
sanitize supports `default value` of `Object type` like the under code.
```
@sanitize.body({
extra: sanitize.Object({}, {def: {}}),
additional: sanitize.Object({}, {def: { noError: true }})
})
```
ps. https://github.com/Atinux/schema-inspector#s_def
> feat: support default value of sanitize Object

- src/controllers/endpoint-decorator.ts
https://github.com/spearhead-ea/island-keeper/pull/17
no longer set the limit at the decorator.
It is only set via api.
Values changed through api are preserved. (https://github.com/spearhead-ea/island-keeper/pull/17)
> changed serviceQuota Decorator

- src/controllers/endpoint-decorator.ts
- src/controllers/rpc-decorator.ts
- src/utils/error.ts
There are 3 points to the key get/set to the consul in the island.
1. islandKeeper init
2. registering endpoint
3. registering rpc
in case 1, the following error is displayed. It does not affect the service. And this error is hard to check.
```
diagnostic_1   | [--------|05:09:34|i] started 
diagnostic_1   | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): Error: Permission denied
```
in case 2, 3.  It does affect the service.
```
Error: Permission denied
at create (/app/be/node_modules/papi/lib/errors.js:14:5)
at Object.response (/app/be/node_modules/papi/lib/errors.js:38:15)
at IncomingMessage.<anonymous> (/app/be/node_modules/papi/lib/client.js:579:26)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT …
```
> changed consul error to FATAL error

- src/adapters/impl/push-adapter.ts
- src/services/push-service.ts
- src/spec/push-service.spec.ts
- Fast and dirty implementation.
- PushService manually selects broker connection using hashKey which is specified or generated by exchange name.
- Unicast exchange is renamed.
- Works using federation (or with manual spreading option enabled.)
- Used for supporting huge number of session queues which makes clusters very slow due to synchronization among nodes.
> Apply manual sharding on PushService

- src/services/push-service.ts
http://git.sphd.io/support/stt-issues/issues/854
support `FORMALIZATION_FORMAT_PUSH`
use Template string
It is used as follows.
```
FORMALIZATION_FORMAT_PUSH = '{"type":"push_all", "resource": [{"resource": "ToastMessage", "path": "$", "body": { "cmd": ${obj.cmd}}, "resource":${JSON.stringify(obj.opts)}}]}'
```
> feat: FORMALIZATION_FORMAT_PUSH

- src/services/push-service.ts
- src/spec/push-service.spec.ts
all encoded packet should have magic number for passing encoding type.
this rule is important because, if some service misconfigure, push
service cannot decode packet.
this patch can start to detecting wrong server configuration.
> Add magic prefix into push packets

- src/services/abstract-broker-service.ts
In rpc-service.ts, used as follows
```typescript
private is503(err) {
return err.statusCode && parseInt(err.statusCode, 10) === 503;
}
```
> fixed the variable referenced incorrectly.

- src/services/rpc-service.ts
it can change the ack setting in the RPC response queue as needed.
For example,
The gateway-island may not need to acknowledge the RPC Response Queue.
When Rabbitmq is under high load, ack can be processed be later than requested. 
In this time, island has been `ack`, but it is not actually processed and stop `consume`.
> feat: rpc Response queue ack option

- src/controllers/endpoint-decorator.ts
- src/controllers/rpc-decorator.ts
- src/index.ts
- src/services/event-service.ts
- src/services/push-service.ts
- src/services/rpc-service.ts
- src/utils/environments.ts
- src/utils/logger.ts
- src/utils/status-exporter.ts
- src/utils/tracelog.ts
If the  value of `NODE_ENV` is development, it is judged to be in a development state.
However, the value of `NODE_ENV ` is a problem because it is commonly used.
Use value of `USE_DEV_MODE` instead of value of `NODE_ENV` to see if it is a development environment.
Provides the value of island environments as function.
It can be used as follows.
```
const devMode = island.Environments.isDevMode();
```
> feat: environment values are provided

- README.md
- src/services/event-service.ts
- src/spec/event-service.spec.ts
- src/utils/environments.ts
**WHY**
* In the case of a cron event, it can also operate up to 1 second. At this time, there are too many logs for the cron event, leaving a lot of meaningless logs.
**After**
* Allows you to limit the cron event log so that no cron is logged.
release_candidate
> feat: restrict console log for cron

- src/adapters/abstract-adapter.ts
- src/adapters/impl/event-adapter.ts
- src/adapters/impl/rpc-adapter.ts
- src/islet.ts
- src/services/event-service.ts
- src/services/rpc-service.ts
- src/spec/event-service.spec.ts
- src/spec/rpc.spec.ts
When a `SIGUSR2(12)` signal occurs,
shows the details of the requests being processed.
```
root@637c222e8847:/app/be/service# kill -12 1
[--------|11:33:53|i] Waiting for a check to process status 
[--------|11:33:53|d] sigInfo :  rpc 
[--------|11:33:53|i] RPC Service onGoingRequestCount : 0 
[--------|11:33:53|d] sigInfo :  event 
[--------|11:33:53|i] RPC Service Info 
[--------|11:33:53|i] RPC Service onGoingRequestCount : 0 
[--------|11:33:53|d] sigInfo :  push 
```
> feat : ongoingRequest detail info

- src/islet.ts
- src/utils/environments.ts
It can ignore Signal.
It can be used if the Queue's Consuming needs to continue, such as `gateway-island`.
> feat: ignore SigTerm signal

- package.json
- src/adapters/listenable-adapter.ts
- src/controllers/endpoint-decorator.ts
- src/controllers/event-decorator.ts
- src/islet.ts
- src/services/abstract-broker-service.ts
- src/services/amqp-channel-pool-service.ts
- src/services/event-service.ts
- src/services/rpc-service.ts
- src/spec/rpc.spec.ts
- src/spec/schema-types.spec.ts
- src/utils/environments.ts
- src/utils/status-collector.ts
- tslint.json
- Bump up lint & typescript version.
- The [type] syntax means tuple.  When define array should use type[]. [typescript spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#385-tuple-type-literals)
- When something can be null, we should use [Definite Assignment Assertions(syntax "!") ](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html).
- process.env type is [string | undefined](https://stackoverflow.com/questions/35666903/typescript-definitions-for-process-env-node-env).
- Remove unused property rpcService.responseConsumerInfo.
> feat: bump up typescript 2.2 to 2.8

- src/index.ts
https://github.com/spearhead-ea/island/issues/204
Adapter options like `RestifyAdapterOptions` should be exported so that implementation code could define object construction parameter explicitly.
**Specially what I need to know is that ALL adapter options interfaces should be exposed or not.**
> fix: export AdapterOptions

- src/services/event-service.ts
a problem that `event.args` may not work normally when doing eventPublish. 
corrected to appear normally as shown below
> fix: abnormal console.log for eventPublish

- src/services/event-service.ts
- src/spec/event-service.spec.ts
- src/spec/rpc.spec.ts
- src/utils/status-collector.ts
* EventService also doesn't use `TraceLog`
> refactor: clean dependencies of EventService

- src/index.ts
export error.ISLAND
you can refer to the error code defined in island.js in xxx-island.
```
const error = Error.splitCode(e.code);
if (error.islandLevel === IslandLevel.ISLANDJS &&
error.errorCode === ISLAND.FATAL.F0023_RPC_TIMEOUT) {
...
}
```
> export error.ISLAND

- src/utils/rpc-response.ts
If not an AbstractError type, use errorCode as err.code
If you do not want to use AbstractError Type, err.code must be less than 1000
> fix : error code

- src/services/message-broker-service.ts
- src/spec/message-broker.spec.ts
`msg-broker` is not more using. so added the `deprecated decorator` to `mgs-broker`
> refactor: deprecated msg-broker

- src/spec/error.spec.ts
- src/utils/error.ts
added `extra` and `statusCode` value to be placed in the Error object.
the error option interface was limited to `extra` and `statusCode` only
> feat: add error option fields for extra &    statusCode

- src/services/event-service.ts
- src/services/rpc-service.ts
* Queues can be deleted by accident
* An island node can be zombie process by the queue deleting
* Fresh dying is better than a half-living
(cherry picked from commit 8c5ce07e7c476532cefb7ebce41e93b82addf9da)
> fix: a potential zombie by MQ shutdown

- src/services/rpc-service.ts
*AS-IS*
* If there is no code in `rpcError`,` gateway` generates error code for gateway
*TO-BE* 
* If there is no code in `rpcError`. `response-island` will create an` unknown error` via this commit.
> refactor: added that making unknown code for rpc, if not exists code

- src/services/event-service.ts
- src/services/rpc-service.ts
- src/spec/diag.spec.ts
- src/spec/rpc-timeout.spec.ts
- src/spec/rpc.spec.ts
- src/utils/env-loader.ts
- src/utils/environments.ts
- src/utils/error.ts
- src/utils/route-logger.ts
fix: Incorrect RPC timeout
**How to use**
Added `timeout` with RPC Invoke option.
default timeout is ISLAND_RPC_EXEC_TIMEOUT (25s)
```
await rpcService.invoke(RPCName, Argument, { timeout?: ms } );
```
**Changes**
- Environments have been removed
`ISLAND_RPC_WAIT_TIMEOUT`
`ISLAND_RPC_WAIT_TIMEOUT_MS`
`ISLAND_SERVICE_LOAD_TIME`
`ISLAND_SERVICE_LOAD_TIME_MS`
- Environments have been added
`ISLAND_RPC_MESSAGE_TTL` : (60s) The time to be cleared after the RPC Message is used
`ISLAND_RPC_REPLY_MARGIN_TIME` :  (1s) This is the appended time for taking occurred timeout error in consume at invoke
- Timeout Error has changed.
AbstractEtcError  -> AbstractError
error.code : 10020001 -> 10010023
error.name: TimeoutError -> FatalError
error.extra has rpcName, parent, waitTime, and location.
+ …
> feat: correct RPC timeout

- src/services/amqp-channel-pool-service.ts
- src/services/rpc-service.ts
* `publish of undefined` whlie sending a RPC at very beginning
* It is caused by making a miscount `idleChannelLength` compared by `idleChannels.length`
> fix: support/stt-issues#2814

- src/services/event-subscriber.ts
can not use more than one same wildcard in PatternSubscriber
> fix: convertRoutingKeyPatternToRegexp

- src/controllers/endpoint-decorator.ts
- src/utils/environments.ts
- src/utils/event.ts
- src/utils/information.ts
Pre-work to not use island-keeper(consul).
Add a common Event.
1. When **SystemHealthCheck** is publish, a **SystemInfo** is raised
2. added and changed known by **SystemInfo**
3. if added or changed, you can publishEvent **SystemEndpointCheck** 
4. When **SystemEndpointCheck** is publish, a **SystemEndpointInfo** is raised
5. you can sync endpoints by **SystemEndpointInfo** 
| Event Name        | Event               | Caller                  | Callee | Trigger |
| ----------------- | ------------------- | ----------------------- | ------ |-------- |
| SystemHealthCheck | System.health.check | gateway-island | island.js | SystemInfo |
| SystemInfo        | System.info.checked | island.js | gateway-island | SystemEndpointCheck |
| SystemEndpointCheck | System.endpoint.check | …
> feat: common system events

- src/islet.ts
- src/utils/environments.ts
If the initialization fails for more than ISLAND_MAX_INITIALIZATION_TIME_MS,
it will be terminated.
ISLAND_MAX_INITIALIZATION_TIME_MS is default 1m.
```
async function sleep(value, millis) {
return new Promise(function (resolve, reject) {
setTimeout(function () { resolve(value); }, millis);
});
}
async function timeout(value, millis) {
return new Promise(function (resolve, reject) {
setTimeout(function () { reject(value); }, millis);
});
}
Promise.all([ sleep(1, 0), sleep(2, 1000), sleep(3, 2000) ]).then(res => console.log('result : ' + res)).catch(e => console.log('error : ' + e));
> result : 1,2,3
Promise.race([ Promise.all([ sleep(1, 0), sleep(2, 1000), sleep(3, 2000) ]),
timeout('timeout', 1500) ]).then(res => console.log('result : ' + res)).catch(e => console.log('error : ' + e));
> …
```
> feat: ISLAND_MAX_INITIALIZATION_TIME

- src/services/event-service.ts
- src/services/rpc-service.ts
   * docker stop
   * sends SIGTERM to the process
   * Islet.js receives SIGTERM
   * Islet.js destroy all adapters
   * Purge the service each adapter is adaptee
   * Typical ListenableAdapters such as RPC and Event do not terminate immediately in the purge situation but finish the handler in process.
   * At this time RPC calls `purging ()` before `channel.ack ()`, so channelPool is `purge()` before `rpc.purging()`
To solve this, moved the position of `purging()` after `channel.ack()`.
> refactor: modified purging loacation for rpcService

- src/utils/event.ts
1.  wrong event class
```[--------|11:09:35|d] subscribe event : system.health.check
[5] =================================== [island] SystemEndpointCheck  SystemHealthCheck {
key: 'system.health.check',
args: {},
publishedAt: 2018-10-22T02:09:34.996Z }```
2. can't not use publishEvent on a island Default Subscirbe event function
```[--------|11:09:40|e] error on handling event {"extra":{"args":{},"event":"system.health.check","island":"gateway-island"}}
[--------|11:09:40|d] publish log.error {
"message": "this.publishEvent is not a function",
"params": {},...```
1. typo event name for SystemEndpointCheck (`SystemHealthCheck` -> `SystemEndpointCheck`)
2. changed `arrow function` -> `function` according to `this`
the second changed contecxt here is explain [this stack over …
> fix: wrong event name & change arrow function

- src/utils/event.ts
when uri conflict, `gateway-island` publish `SystemEndpointConflict` Event.
when this event is received, The warning is output.
<hr> 
uri가 충돌날 경우 gateway-island로부터 `SystemEndpointConflict` Event를 받습니다.
이 이벤트를 받을 경우 warning을 출력합니다.
> feat: Endpoint Conflict

- src/services/amqp-channel-pool-service.ts
- src/spec/amqp-channel-pool.spec.ts
fix: construct amqp pool service object for every unittest
fix: more strict unit test pass condition
> fix: purge channels and reset idleChannelLength.

- .travis.yml
- README.md
- src/services/amqp-channel-pool-service.ts
- src/utils/diag-cli.ts
fix: added exception logic for unit test to NOT terminate process
This is to fix a bug that island process keeps alive when its AMQP connection is closed by external cause.
amqp.connection.on('close') handler is to terminate process when the connection is closed.
amqp.connection.on('error') handler is to store log. when 'error' event occurred, 'close' event will be emitted.
amqp.connection.on('blocked') handler is to terminate process when the connection is blocked by broker. reason of blocking situation varies by broker's condition.
ref: http://www.squaremobius.net/amqp.node/channel_api.html#models
NOTE:
.travis-ci is fixed to add `UNIT_TEST=true` env to ignore connection event handler for UNIT TEST process.
> fix: added amqp connection event handlers

- src/spec/rpc.spec.ts
Test case "should ensure the uuid of the error raised by the RPC which has been timed out" fails randomly. It may be occured 3 or 4 times on 10 times try. 
That test case tests whether uuid is registered when RPC time out occur. To regenerate time out, test case invokes unregistered RPC. Invoking unregistered RPC make channel close. 
```
await rpcService.register('out', async () => {
return rpcService.invoke('unmethod', 'arg'); // way to make time out
}, 'rpc');
```
When time out exception is thrown rpcService send ack to channel which is already closed.
```
rpc-service.ts
try {
await handler(msg);
if (!noAck) channel.ack(msg);
} catch (error) {
// ...
// Here, channel may be closed already randomly when 404 error occur by above code
if (!noAck && msg) channel.ack(msg);  
} finally {
// …
```
> fix timed out RPC uuid test failure

- package.json
- src/adapters/impl/mongoose-adapter.ts
- src/islet.ts
- src/utils/environments.ts
Bug Fix context
* Fixed that promise could not be caught if an error occurred in dns.lookup
* Added `adapter initilize timeout` that merged already in master branch
> Fix can not catch error mongo

- scripts/docker-entrypoint.sh
http://git.sphd.io/support/stt-issues/issues/3195
When there are multiple 'name' within package.json, only grep first
> fix: grep command to get first only

- src/controllers/event-decorator.ts
- src/services/event-service.ts
- src/services/event-subscriber.ts
- src/spec/event-service.spec.ts
- src/utils/environments.ts
Add the event Service option.
`guaranteeArrivalTime` Setting ignores this event if the Event arrives later than `Environments.AllowedArrivalTime(Default 2 Sec)`.
It is used as follows.
```
@subscribePattern('cron.s.#.00', { guaranteeArrivalTime: true })
```
<hr>
이벤트 서비스에 `guaranteeArrivalTime` 옵션을 추가합니다.
이 옵션이 사용될 경우 이벤트가 `Environments.AllowedArrivalTime(기본값 2초)`보다 늦게 도착할 경우 실행되지 않고 무시됩니다.
> feat: new event options, guaranteeArrivalTime

- src/services/amqp-channel-pool-service.ts
When channel closed, channel try to remove itself from idleChannels. But it would not removed because channel remove statement could be run before marking terminate is finished due to missing `return` statement before `obj.then( ... )`. It returns void promise and not wait obj.then.
```
private async setChannelEventHandler(channel: amqp.Channel) {
channel
.on('error', err => {...})
.on('close', async () => {
await Promise.all(_.map(this.idleChannels, async obj => {
obj.then( value => {
if ( (value as any).ch === (channel as any).ch) {
(obj as any).terminate = true;
}
});
}));
_.remove(this.idleChannels, obj => { 
return (obj as any).terminate;
});
});
}
```
resolve this by adding `return` statement before `obj.then(...)`.
> fix:channel is not removed from idleChannels when channel closed
