src/index.ts, src/utils/jasmine-async-support.ts
- spy화된 객체의 함수 호출 횟수를 초기화하는 헬퍼 함수 추가
=> add jasmine utility

.travis.yml, package.json, src/islet.ts
State flow -
* run - `Islet`(static)
* main - `Islet`
* initialize - `Islet`
* onPrepare - `Islet` <- newly added
* initialize - `AbstractAdapter`s
* onInitialized - `Islet`
* postInitialize - `ListenableAdapter`s
* listen - `ListenableAdapter`s
* onStarted - `Islet`
=> Add support to prepare initialize of any adapters

src/controllers/rpc-decorator.ts, tslint.json
- Fix compile error by @types/lodash 7ee1e51
=> Merge release-1.5 into master

src/services/amqp-channel-pool-service.ts
src/services/amqp-channel-pool-service.ts(66,48): error TS2532: Object is possibly 'undefined'.
=> Fixed undefinedError

src/services/event-service.ts, src/services/rpc-service.ts, src/spec/event-service.spec.ts, src/spec/rpc-spec.ts
fix #81 
Expand an existing RPC hook system to support custom error handler - now we have
```ts
export enum RpcHookType {
PRE_ENDPOINT,
POST_ENDPOINT,
PRE_RPC,
POST_RPC,
PRE_ENDPOINT_ERROR,   // newer
POST_ENDPOINT_ERROR,  // newer
PRE_RPC_ERROR,        // newer
POST_RPC_ERROR        // newer
}
```
Add a hook system for Event also.
```ts
export enum EventHookType {
EVENT,
ERROR
}
```
=> feat(event): rpc error hook and event hooks

package.json, src/adapters/impl/mongoose-adapter.ts
=> feat: add function to change hostname to ip

package.json, src/adapters/impl/rpc-adapter.ts, src/services/rpc-service.ts
and RpcResponse#reviver has no chance to get back
=> fix: RPCAdapter don't pass noReviver to adaptee

package.json, src/services/rpc-service.ts
Fix: noReviver
https://github.com/spearhead-ea/island/commit/b13f8071ec8627d10620a7f9d9974cd56b007dab
https://github.com/spearhead-ea/island/commit/87fc40db65ca29b5ab40bc8676024f14f7b660f0
=> Merge from Release 1.6 into master

src/services/amqp-channel-pool-service.ts
add a name field on amqpOptions for connection logs
=> refact: Add name on AmqpOptions

package.json, src/adapters/impl/amqp-channel-pool-adapter.ts, src/adapters/impl/mongoose-adapter.ts, src/adapters/impl/redis-connection-adapter.ts, src/adapters/impl/restify-adapter.ts, src/controllers/endpoint-decorator.ts, src/controllers/rpc-decorator.ts, src/index.ts, src/islet.ts, src/services/event-service.ts, src/services/event-subscriber.ts, src/services/rpc-service.ts, src/spec/event-service.spec.ts, src/spec/interval-service.spec.ts, src/spec/rpc-spec.ts, src/utils/interval-helper.ts
* Rpc, Event Service graceful purge 
* Use 'check processing request' to do purge after service processing finishes
* after OtherService purge, Islet destroy and process.exit(1)
=> feat: Event, RPC Service purge for graceful stop

package.json, src/services/amqp-channel-pool-service.ts
add log for amqp connected log
and fix "types/node" version to "7.0.29"
=> fix: add log for amqp connected & fix @type/node version

src/islet.ts
I think, it would be a mistake. isn't it?
=> add missing 'await' on destroy()

package.json
@types/blubird version was fixed for ts2.2
RELEASE_CANDIDATE
=> fix: @types/bluebird version fix

src/controllers/endpoint-decorator.ts
add Group Quota Options
@island.groupQuota([group1, gropu2])
'group1' is the group name of Quota Group.
Group name is a unique value of quota for EndPoints
=> add Group Quota EndpointOptions

package.json, src/controllers/endpoint-decorator.ts
- modify ensure level Session -> Token
=> refactor: modify ensure default value (SESSION -> TOKEN)

package.json, src/services/push-service.ts
=>  release 1.7 into master

package.json, src/controllers/endpoint-decorator.ts, src/middleware/schema-types.ts, src/spec/push-service.spec.ts, src/spec/schema-decorator.spec.ts, src/spec/schema-types.spec.ts
support minLength, maxLength with validate.Array
validate.Array([validate.ObjectId], {minLength: 1, maxLength: 50})
http://git.sphd.io/support/stt-issues/issues/388
new Schema Type html (require donghlee)
RELEASE_CANDIDATE
=> support minLength, maxLength with Array

package.json, src/index.ts, src/services/push-service.ts
**AS-IS**
- Only have a broadcast messages to all connected Client
**TO-BE**
- According to connect Client classification have a broadcast message for Pc or Mobile
=> feat: add push broadcast type

package.json, src/index.ts, src/services/push-service.ts, src/spec/push-service.spec.ts
- According to connect Client classification have a broadcast message for Pc or Mobile
https://github.com/spearhead-ea/island/pull/125
=> Cherrypick.from.master

src/services/event-service.ts, src/services/rpc-service.ts
=> Hot-fix #127 into release-1.7

src/controllers/endpoint-decorator.ts, src/spec/schema-decorator.spec.ts
http://git.sphd.io/support/stt-issues/issues/674
Support 'exactLength' of Array for validating.
=> Support exactLength of Array for validating .

src/controllers/endpoint-decorator.ts
add serviceQuota at endpoint options
=> add service Quota - RELEASE_CANDIDATE

src/controllers/endpoint-decorator.ts
when register endpoint, call saveEndpoint after registerEndpoint
dependecies : https://github.com/spearhead-ea/island-keeper/pull/23
=> [RELEASE_CANDIDATE] when register endpoint, call saveEndpoint after registerEndpoint

src/controllers/endpoint-decorator.ts
fixed registerEndpoint return method
=> fixed registerEndpoint return method

src/controllers/endpoint-decorator.ts
https://github.com/spearhead-ea/island/pull/152
https://github.com/spearhead-ea/island/pull/151
It reflects the test result.
The following issues have been found:
1. Issue with multi-controllers used
=> fixed test result, release_candidate

src/index.ts
fixed missing quota options at index.ts
=> fix: missing quota at index.ts

src/services/push-service.ts
I remove previously added features(https://github.com/spearhead-ea/island/pull/158) to do find a better way.
It will develop in push-island to support Custom push format
=> fix: remove custom_push_format release_candidate

package.json
=> feat: major version up as 3.0.0-dev

src/adapters/impl/mongoose-adapter.ts, src/adapters/impl/redis-connection-adapter.ts
add mongo connection log
add redis connection log
http://git.sphd.io/support/stt-issues/issues/932
=> Feat.add.log.mongo-redis.connected

src/adapters/impl/rpc-adapter.ts, src/services/rpc-service.ts
http://git.sphd.io/support/stt-issues/issues/1180
=> feat: split pub/sub mq channel for RPC

src/adapters/impl/socketio-adapter.ts
[@types/socket.io new version(1.4.32) commint](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/52bde4982f4f477f815fb2a484c584c9cf9109c0)
Modifying the code to reflect the content.
=> fix: reflect correction to updating @types/socket.io:1.4.32

src/islet.ts
=> fix: collector.saveStatus must bind this

src/services/event-service.ts
Fixes a bug on exchange name that changes based on the number of arguments.
=> fix: exchange at publishEvent

src/services/rpc-service.ts
=> feature: add console log for ISLAND_TRACE_HEADER_LOG

README.md, src/spec/rpc.spec.ts, src/utils/environments.ts, src/utils/status-collector.ts
This is an example for @jiho-kr job.
It will modify the merge to make it easier for @jiho-kr to use
=> feat: add event option for status export

src/index.ts, src/services/rpc-service.ts, src/spec/env-loader.spec.ts, src/spec/rpc.spec.ts, src/utils/env-loader.ts, src/utils/environments.ts
Add Decorator - Load Environment
Rename Environment Properties - ISLAND_ prefix for all properties
=> Feat.load.environment.with.decorator

package.json, src/adapters/impl/middlewares/restify-jwt-middleware.ts, src/adapters/impl/middlewares/restify-session-middleware.ts, src/adapters/listenable-adapter.ts, src/controllers/endpoint-decorator.ts, src/controllers/event-decorator.ts, src/index.ts, src/services/rpc-service.ts, src/spec/env-loader.spec.ts, src/spec/rpc.spec.ts, src/utils/env-loader.ts, src/utils/environments.ts, src/utils/interval-helper.ts, src/utils/status-collector.ts, tslint.json
refactor: applied tslint rules. disabled max-file-line-count option
issue # : https://github.com/spearhead-ea/island/issues/195
=> fix: upgrade gulp-tslint to make it work properly.

package.json, src/islet.ts
reflect https://github.com/spearhead-ea/island/pull/183
=> feat: ignore SigTerm signal

package.json
island-di 버전이 항상 최신으로 반영되어서 이슈가 발생.
=> fixed version for island-di in package.json

README.md, src/adapters/impl/rpc-adapter.ts, src/islet.ts, src/services/rpc-service.ts, src/spec/rpc.spec.ts, src/utils/environments.ts
It is no longer defaulted to the reviver option
Change to NO_REVIVER -> USE_REVIVER option
=> refactor: NO_REVIVER -> USE_REVIVER

src/islet.ts
Master PR
You can see that island has been destroyed.
```
isDestroyed() : boolean
```
ignore SIGINT signal
https://github.com/spearhead-ea/island/pull/255
=> feat: isDestroyed & ignore SIGINT

README.md
=> fix: README.md for test

README.md, package.json
http://git.sphd.io/support/stt-issues/issues/3095
Review @wokim @heycalmdown @Ohen @resoliwan @UniverseHan @jiho-kr @sejeong @sshtel
=> fix: removing @types/winston

src/spec/events.spec.ts
island-logger PR should be merged. (https://github.com/spearhead-ea/island-loggers/pull/16)
add Spec, Events.LoggerLevelChanged
=> spec: Events.LoggerLevelChanged
